facturas/urls.py
from django.urls import path
from facturas.views import factura, tfactura, vfactura,  detalle, factura_estado,detalle_estado, factura_eliminar, vfactura, facturaInacti
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('crearfactura/', factura, name='factura-factura'),
    path('factura/', tfactura, name='factura-tfactura'),
    path('detalle/<int:pk>/', detalle, name='factura-detalle'),
    path('facturai/', facturaInacti, name='factura-facturai'),
    path('detalle-factura/estado/<int:pk>/<str:estado>/', factura_estado, name='factura_estado'),
    path('detalle-estado/eliminar/<int:pk>/<str:cantidad>', detalle_estado, name='detalle_eliminar_estado'),
    path('verfactura/<int:pk>', vfactura, name='factura-verfactura'),
    path('eliminar/<int:pk>/', factura_eliminar, name='factura_eliminarA'),
]

 

gestion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views 
from gestion.views import index, inicio, backup, ayudausuario, ayudainicio, ayudaindex


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name="index"),
    path('inicio/',inicio, name="inicio"),
    path('factura/', include('facturas.urls')),
    path('pago/', include('pago.urls')),
    path('usuario/', include ('usuarios.urls')),
    path('producto/', include('productos.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='usuario-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='usuario-logout'),
    path('registrar/',include('cuenta.urls')),
    path('backup/<str:tipo>/', backup , name="backup"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',email_template_name='registration/password_reset_email.html'),
         name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('ayudainicip/', ayudainicio, name="ayudainicio"),
    path('ayudausuario/', ayudausuario, name="ayudausuario"),
    path('ayudaindex/', ayudaindex, name="ayudaindex"),
    
]+ static(
    settings.MEDIA_URL, 
    document_root = settings.MEDIA_ROOT)

    
    # path('reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
    #         'email_template':'registration/password_reset_email.html'}, name='password_reset'),
    # path('reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},
    #         name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>)/$',password_reset_confirm,
    #      name='password_reset_confirm'),
    # path('reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'},
    #         name='password_reset_complete'),
    

pago/urls.py
from django.urls import path
from pago.views import pago,tpago,pago_detalle,pago_estado, vpago,detalle_estado
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('crearpago/', pago, name='pago-pago'),
    path('pago/', tpago, name='pago-tpago'),
    path('pago/<int:pk>/', pago_detalle, name='pago-detalles'),
    path('detalle-pago/estado/<int:pk>/<str:estado>/', pago_estado, name='pago_estado'),
    path('ver_pago/<int:pk>', vpago, name='pago-verpago'),
    path('detalle-pago/eliminar/<int:pk>/<str:cantidad>', detalle_estado, name='detalle_eliminar'),    
]

 

facturas/models.py
from xml.etree.ElementInclude import default_loader
from django.db import models
from django.utils.translation import gettext_lazy as _
from usuarios.models import  Usuario,Rol
from productos.models import Producto

class Factura(models.Model):
    fecha=models.DateField(auto_now = True, verbose_name="Fecha de factura", help_text=u"MM/DD/AAAA")
    rol=models.ForeignKey(Rol, on_delete=models.SET_NULL, null=True,verbose_name="Rol")
    usuario=models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True,verbose_name="Nombre")
    tipofactura= models.CharField(max_length=10, verbose_name="Tipo de factura")
    neto_pagar=models.IntegerField(default=0)
    class Estado(models.TextChoices):
        ABIERTA='Abierta', _('Abierta')
        CERRADA='Cerrada', _('Cerrada')
        ANULADa='Anulada', _('Anulada')
    estado= models.CharField(max_length=10, choices=Estado.choices, verbose_name="Estado", default=Estado.ABIERTA)
    class Decision(models.TextChoices):
        ACTIVO= 'Activo', _('Activo')
        INACTIVO= 'Inactivo', _('Inactivo')
    decision= models.CharField(max_length=10, choices=Decision.choices, verbose_name="Estado", default=Decision.ACTIVO)
    class Meta:
        db_table="facturas_factura"
        


class Detalle(models.Model):
    factura=models.ForeignKey(Factura, on_delete=models.SET_NULL, null=True,verbose_name="Factura")
    producto=models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True,verbose_name="Producto")
    class Estado(models.TextChoices):
        ABIERTA='Abierta', _('Abierta')
        CERRADA='Cerrada', _('Cerrada')
        ANULADa='Anulada', _('Anulada')
    estado= models.CharField(max_length=10, choices=Estado.choices, verbose_name="Estado", default=Estado.ABIERTA)
    cantidad_detalle=models.IntegerField(default=0) 
    total=models.IntegerField(default=0)
    precioX=models.IntegerField(default=0)
   
    def __str__(self)-> str:
        return '%s' % (self.id)
    

gestion/models.py
from django.db import models

def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.sql']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Archivo no válido')

class Backup(models.Model):
    nombre = models.CharField(max_length = 200,default="Copia de Seguridad", blank=True)
    archivo = models.FileField(upload_to = "backup",validators=[validate_file_extension])
    fecha = models.DateTimeField(auto_now = True)
    
   

facturas/forms.py
from tkinter import Widget
from django import forms
from facturas.models import Factura, Detalle

class FacturaForm(forms.ModelForm):
    class Meta: 
        model = Factura
        fields = []
        
class DetalleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DetalleForm, self).__init__(*args, **kwargs)
        self.fields['cantidad_detalle'].widget.attrs['min'] = 1
        
    def clean_price(self):
        price = self.cleaned_data['price']
        if price < 1:
            raise forms.ValidationError("Price cannot be less than 0.01")
        return price

    class Meta: 
        model = Detalle
        fields = ['cantidad_detalle']
        

gestion/forms.py
from django import forms
from django.forms import ModelForm
from gestion.models import Backup


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

class BackupForm(ModelForm):
    class Meta:
        model= Backup
        fields= ['nombre','archivo']

facturas/views.py
import imp
from math import prod
from re import I
from django.shortcuts import render, redirect
from facturas.models import Factura, Detalle,Producto
from facturas.forms import FacturaForm, DetalleForm
from django.contrib import messages
from usuarios.models import Rol, Usuario
from productos.models import Producto
from datetime import datetime
from django.db.models import Sum
from django.db import models
from django.contrib.auth.decorators import login_required

@login_required(login_url="usuario-login")
def factura(request):
    rol_c=Rol.objects.all()
    usuario_c=Usuario.objects.all()
    
    facturadb = Factura.objects.all()
    if request.method == 'POST':
        
        form = FacturaForm(request.POST)
        if Factura.objects.filter(usuario=request.POST['usuario'],estado="Abierta"):
            form = FacturaForm()
            messages.warning(request,f'Ya hay una factura creada de ese usuario')
            return redirect('factura-tfactura')
        else:
            if form.is_valid():
                usuario= Usuario.objects.get(Uid=request.POST['usuario']),
                
                aux= Factura.objects.create(
                    rol_id= request.POST['rol'],
                    usuario= usuario[0],
                )
                if(usuario[0].rol.Rnombre == 'Cliente' ):
                    tipo='Venta'
                else:
                    tipo='Compra'
                
                
                Factura.objects.filter(id=aux.id).update(  
                    tipofactura=tipo
                )
                messages.success(request,f'Factura agregada correctamente') 
                return redirect('factura-detalle',aux.id)
    else:
        form = FacturaForm()
    context={
        'base_datos':facturadb,
        'form':form, 
        "rol":rol_c,
        "usuario":usuario_c
    }
    return render(request,'factura/crearFactura.html', context)

@login_required(login_url="usuario-login")
def tfactura(request):
    titulo_pagina="Factura"
    tfacturas= Factura.objects.all()
    context={
        "tfacturas": tfacturas,
        "titulo_pagina": titulo_pagina
    }
    return render(request, "factura/factura.html",context)

@login_required(login_url="usuario-login")
def vfactura (request,pk):
    titulo_pagina="Factura"
    factura= Factura.objects.get(id=pk)
    detalles= Detalle.objects.filter(factura_id=pk)
    print(detalles)
    context={
        "factura": factura,
        "titulo_pagina":titulo_pagina,
        "detalles":detalles
    }
    return render(request,"factura/verfactura.html", context)


@login_required(login_url="usuario-login")
def factura_eliminar(request,pk):
    titulo_pagina='Factura'
    tfacturas= Factura.objects.all()
    tfactura= Factura.objects.get(id=pk)
    accion_txt= f" la factura {tfactura.id}"
    if request.method == 'POST':
        form = FacturaForm(request.POST)
        Factura.objects.filter(id=pk).update(
                    decision='Inactivo'
                )
        tfactura_usuario=  tfactura.usuario
        messages.success(request,f'Factura {tfactura.id} anulada correctamente')
        return redirect('factura-tfactura')
                
    else:
        form:FacturaForm()
    context={
            "titulo_pagina": titulo_pagina,
            "accion_txt":accion_txt,
            "tfacturas": tfacturas,
            
    }
    return render(request, "factura/factura-eliminar.html", context)


@login_required(login_url="usuario-login")
def detalle(request,pk):#pk es el id de la factura
    titulo_pagina="facturas"
    detalles= Detalle.objects.filter(factura_id=pk)
    factura_u=Factura.objects.get(id=pk)
    
    
    #Suma los precios y da un total
    if(Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))):
        total= Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))[0]["total_definitivo"]
    else:
        total=0
    #Filtrando productos para visualizacion del cliente
    if factura_u.rol.Rnombre == 'Cliente':
        productos= Producto.objects.filter(estado="Activo")
    else:
        productos= Producto.objects.filter(usuario=factura_u.usuario, estado="Activo")
    
    if request.method == 'POST':
        form= DetalleForm(request.POST)
        if form.is_valid():    
            producto= Producto.objects.get(id=request.POST['producto'])
            if factura_u.tipofactura =="Compra":
                existe= Detalle.objects.filter(factura=pk,producto=producto)
                if len(existe) == 0:
                    Detalle.objects.create(
                            cantidad_detalle= form.cleaned_data.get('cantidad_detalle'),
                            total= producto.precio *  form.cleaned_data.get('cantidad_detalle'),                                                          
                            factura=factura_u,               
                            producto = producto,
                            precioX= producto.precio
                    )
                    
                    
                    Producto.objects.filter(id=producto.id).update(
                        stock=producto.stock + form.cleaned_data.get('cantidad_detalle')
                    
                    )

                    if(Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))):
                        total= Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))[0]["total_definitivo"]
                        Factura.objects.filter(id=pk).update(
                            neto_pagar=total                
                        )
                    else:
                        total=0
                    

                    
                    messages.success(request,f' se agregó {producto} a la factura correctamente')
                    return redirect('factura-detalle', pk=pk)
                else:
                    anterior=Detalle.objects.filter(factura_id=pk,producto=request.POST['producto'])
                    
                    Detalle.objects.filter(factura_id=pk,producto=request.POST['producto']).update(
                        cantidad_detalle=anterior[0].cantidad_detalle + form.cleaned_data.get('cantidad_detalle'),
                        total=anterior[0].total + producto.precio * form.cleaned_data.get('cantidad_detalle'),
                    )
                    
                    Producto.objects.filter(id=producto.id).update(
                            stock=producto.stock + form.cleaned_data.get('cantidad_detalle')
                        
                        )
                    if(Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))):
                        total= Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))[0]["total_definitivo"]
                        Factura.objects.filter(id=pk).update(
                            neto_pagar=total                
                    )
                    else:
                        total=0
                    
                    Factura.objects.filter(id=pk).update(
                            neto_pagar=total                
                    )

            else:
                if(producto.stock >= int(request.POST['cantidad_detalle'])):
                    existe= Detalle.objects.filter(factura_id=factura_u.id,producto=producto)
                    cantidadA= Usuario.objects.filter(rol=1)
                    print(cantidadA)
                    if len(existe) == 0: 
                        
                        factura= Detalle.objects.create(
                                cantidad_detalle= form.cleaned_data.get('cantidad_detalle'),
                                total= producto.precio_venta *  form.cleaned_data.get('cantidad_detalle'),                                                          
                                factura=factura_u,               
                                producto = producto,
                                precioX= producto.precio_venta 
                        )
                        
                        
                        
                        Producto.objects.filter(id=producto.id).update(
                            stock=producto.stock - form.cleaned_data.get('cantidad_detalle')
                        
                        )
                        
                        if(Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))):
                            total= Detalle.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'),output_field=models.IntegerField()))[0]["total_definitivo"]
                            Factura.objects.filter(id=pk).update(
                            neto_pagar=total                
                        )
                        else:
                            total=0
                        
                        messages.success(request,f' se agregó {producto} a la factura correctamente')
                        return redirect('factura-detalle', pk=pk)
                    else:
                        anterior=Detalle.objects.filter(factura_id=factura_u.id,producto=request.POST['producto'])
                        
                        anterior.update(
                            
                            cantidad_detalle=anterior[0].cantidad_detalle + form.cleaned_data.get('cantidad_detalle'),

gestion/templates/factura/asociada-eliminar.html
{% include "factura/asociada.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/modal-eliminarAsociada.html" %}

{% endblock %}

gestion/templates/factura/asociada-estado.html
{% include "factura/detalle-factura.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/estado-detalle.html" %}

{% endblock %}

gestion/templates/factura/asociada.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}

{% block contenido %}
<div class="container">
 
    <div class="row ">
        <a href=" {% url 'factura-tfactura' %}" class="btn d-flex justify-content-center " style=" margin-top: 25px; margin-bottom: 25px; width: 65px; " >
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class=" opcionesTabla bi bi-arrow-left-square-fill  " viewBox="0 0 16 16">
            <path d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z"/>
            </svg>
        </a>
    </div>
    <div class="row p-1">
        <div class="col-md-4">
            <div class="border bg-white p-3">
                <h4>Pago Asociada {{factura.id}}</h4>
                <hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div id="div_id_producto" class="mb-3"> <label for="id_producto" class="form-label requiredField">
                        Producto<span class="asteriskField">*</span> 
                      </label> 
                      <select name="producto" class="select form-select" required="" id="id_producto"> 
                        <option value="" selected="">---------</option> 
                          {% for producto in productos %}
                          <option value="{{producto.id}}" >{{producto}}</option>
                          {% endfor %}
                      </select> </div>
                    {{ form|crispy }}
                    <input class="btn btn-success btn-block "
                        type="submit" Value="Agregar Factura">
                        <a class="btn btn-danger btn-block text-light"
                        href="{% url 'factura_estadoA' pk=factura.id estado='cerrar' %}" >Cerrar Factura</a>
                </form>
            </div>
        </div>

        <div class="col-md-8 p-4 bg-tabla">
            <p class="txtMainI">Factura  {{factura.id}}</p>
            <table class="table bg-white table-bordered results " id="tabla">
                    <thead class="theadtable">
                      <tr class="text-white odd">
                            <th scope="col" >Producto</th>
                            <th scope="col" >Cantidad</th>
                            <th scope="col" >Pago vendedora </th>
                            <th scope="col" >Total</th>
                            <th scope="col" >Estado</th>
                            
                            <th scope="col" class="dt-body-right dtr-hidden">Opciones</th>
                        </tr>
                            
                    </thead>
                    <tbody>
                        {% for asociada in asociadas %}
                        <tr>
                            <td>{{asociada.producto}}</td>
                            <td>{{asociada.cantidad}}</td>
                            <td>{{asociada.}}</td>
                            <td>{{asociada.}}</td>
                            <td>{{asociada.}}</td>
                            <td><a href="{% url 'asociada_eliminar' asociada.id  %}"><svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="opcionesTabla bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>  
        </div>
    </div>
</div>
{% endblock contenido %}

   

gestion/templates/factura/crearFactura.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}
{% block title %} Factura {% endblock title %}
{% block contenido %}

<div class="d-flex flex-row mx-auto formularioProducto container ">

    <div class="d-flex flex-row  mx-auto  ">
        <div class="derecha width-botton">
            <a class="width-a" href=" {% url 'factura-tfactura' %}" class="btn d-flex justify-content-center " alt="Marca"  title="Regresar">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="devolver opcionesTabla bi bi-arrow-left-square-fill  " viewBox="0 0 16 16">
                    <path d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z"/>
                    </svg>
            </a>
        </div>
<div class="my-5 fondoFormulario ">
                <div class="container">
                <div class=" ">
                    <div class="row">
                        <h4 style="width: 240px;">Agregar factura</h4>
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" style="width: 40px;" class="bi bi-info-square" viewBox="0 0 16 16">
                            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                            <title> Cliente: venta / Asociada o Proveedor: Compra</title>
                            
                        </svg>
                    </div>
                    
                <form action="" method="POST">
                    <div id="div_id_rol" class="mb-3"> 
                    <label for="id_rol" class="form-label requiredField">Rol<span class="asteriskField">*</span></label> 
                        <select  name="rol" class="select form-select " required="" id="select1"> 
                            
                            <option selected disabled="true" >--- Seleccione el rol ---</option>
                            {% for ro in  rol %}
                            <option  value="{{ro.Rid}}" >{{ro.Rnombre}}</option>
                            {% endfor  %}
                            
                        </select>
                    </div>

                    <div id="div_id_usuario" class="mb-3">
                        <label for="id_usuario" class="form-label requiredField">Nombre<span class="asteriskField">*</span></label> 
                        <select name="usuario" class="select form-select " required="" id="select2"> 
                                
                            <option selected disabled="true">--- Seleccione el usuario ---</option>    
                            {% for items in usuario %}
                            <option  data-index-number="{{items.rol_id}}|{{items.estado}}" value="{{items.Uid}}">{{items.Unombre}}</option>
                            {% endfor %}

                        </select>
                    </div>

                    {% csrf_token %}
                    {{form|crispy}}

                    <button class="btn btn-primary my-3" type="button" value="Agregar usuario" data-bs-toggle="modal" data-bs-target="#exampleModal"><svg xmlns="http://www.w3.org/2000/svg" width="40"  fill="currentColor" class="bi bi-hdd" viewBox="0 0 16 16">
                    <path d="M4.5 11a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zM3 10.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                    <path d="M16 11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V9.51c0-.418.105-.83.305-1.197l2.472-4.531A1.5 1.5 0 0 1 4.094 3h7.812a1.5 1.5 0 0 1 1.317.782l2.472 4.53c.2.368.305.78.305 1.198V11zM3.655 4.26 1.592 8.043C1.724 8.014 1.86 8 2 8h12c.14 0 .276.014.408.042L12.345 4.26a.5.5 0 0 0-.439-.26H4.094a.5.5 0 0 0-.44.26zM1 10v1a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1z"/>
                    </svg> Guardar
                    </button>

                    <div class="conainer p-3" data-bs-toggle="modal">
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">           
                                        <button type="button" class="btn-close btn-btn-light" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <h5 class=" text-center" id="exampleModalLabel">Confirmar</h5>
                                        <h6 class="modal-title" id="exampleModalLabel">¿Desea guardar?</h6>
                                    </div>
                                        <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" id="liveToastBtnError" data-bs-dismiss="modal" >No</button>
                                        <button type="submit" class="btn btn-success" id="liveToastBtnExito" data-bs-dismiss="modal" >Si</button>    
                                    </div>
                                    <div aria-live="polite" aria-atomic="true" class="position-relative">
                                    </div>
                                </div>
                            </div>
                        </div>           

                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock contenido %}

gestion/templates/factura/detalle-eliminar.html
{% include "factura/detalle-factura.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/modal-eliminarDetalle.html" %}

{% endblock %}

gestion/templates/factura/detalle-estado .html
{% include "factura/detalle-factura.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/estado-detalle.html" %}

{% endblock %}

gestion/templates/factura/factura-eliminar.html
{% include "factura/factura.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/eliminar-factura.html" %}

{% endblock %}

gestion/templates/factura/factura-estado.html
{% include "factura/factura.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/estado-factura.html" %}

{% endblock %}

gestion/templates/factura/factura-estadoAso.html
{% include "factura/factura.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}



{% include "modals/estado-factura.html" %}

{% endblock %}